name: ng_bootstrap
version: 0.4.2
description: Angular 2 and Bootstrap 4
authors:
  - Luis Vargas <luisvargastijerino@gmail.com>
  - Adao Jr. <itsjunnior@gmail.com>
homepage: https://github.com/dart-league/ng_bootstrap
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  angular2: ^2.0.0-beta.22
  browser: ^0.10.0
  node_shims: ^0.1.3
  intl: ^0.13.0
  dart_to_js_script_rewriter: ^1.0.1
  markdown: ^0.8.0
  stream_transformers: ^0.3.0+3
  font_awesome: ^4.6.3
  dson: ^0.3.4
  reflectable: ^0.5.4
  dev_string_converter: ^0.1.0
transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
    - package:angular2/common.dart#COMMON_PIPES
- dart_to_js_script_rewriter
- $dart2js:
    $include: web/index.dart
